export const GET_PROD_LOADING = 'admin/products/loading'
export const GET_PROD_SUCCESS = 'admin/products/success'
export const GET_PROD_FAIL = 'admin/products/fail'
export const ADD_PROD_LOADING = 'admin/products/add/loading'
export const ADD_PROD_ERROR = 'admin/products/add/error'
export const ADD_PROD_SUCCESS = 'admin/products/add/success'
// export const ADD_PROD_ = 'admin/products/loading'